const projects = [
  {
    id: 1,
    image: "./img/project/Burzilla.png",
    title: "Burzilla",
    language: "HTML",
    description: "is a prototype website for a company that sells burgers.",
    descriptionDetail:
      "Burzilla is a company website for a gourmet burger business, designed to introduce the brand and showcase its delicious burger offerings to a wider audience. Built with HTML and Bootstrap, the website features a responsive and modern layout, allowing visitors to easily explore the menu, check out promotions, and find contact information for orders. The clean, visually appealing design enhances user experience while effectively promoting Burzilla’s products.",
    descriptionDetail2:
      "More than just a digital menu, this website serves as a professional branding tool, reinforcing Burzilla’s identity as a high-quality burger provider. Key sections like a product gallery and customer testimonials help build trust and engagement. Whether accessed on desktop or mobile, the site ensures smooth navigation, making it simple for customers to discover what makes Burzilla’s burgers special.",
    githubLink: "https://github.com/HasthoRahtomo/burzilla",
  },
  {
    id: 2,
    image: "./img/project/Mainstore Database System.png",
    title: "Mainstore DB",
    language: "mySQL",
    description: "Database for Mainstore project.",
    descriptionDetail:
      "This is a database code and layout for Mainstore Project. We used mySQL server with XAMPP to let the project store data in it.",
    descriptionDetail2:
      "This database contains table, trigger, view, etc. It will help the project to get the desired data with simple step, but still safe.",
    pptLink: "./docs/MainStoreDB.pdf",
  },
  {
    id: 3,
    image: "./img/project/mainstore.png",
    title: "Mainstore",
    language: "PHP",
    description: "mainstore is a store that sell games and ingame currencies.",
    descriptionDetail:
      "Mainstore is an online gaming marketplace where users can purchase digital games and top-up credits for their favorite games. Built with PHP, Bootstrap, and SQL, this platform offers a seamless shopping experience with secure transactions, an intuitive user interface, and a well-organized game catalog. Users can browse different game categories, check prices, and make purchases with ease. The website also features an admin panel for managing products, orders, and user accounts efficiently.",
    descriptionDetail2:
      "With a responsive design powered by Bootstrap, Mainstore ensures smooth navigation on both desktop and mobile devices. The SQL database securely stores user data, game listings, and transaction records, while PHP handles dynamic content and backend operations. Whether users are looking to buy the latest games or top up in-game currency, Mainstore provides a reliable and user-friendly solution for all gaming needs.",
    githubLink: "https://github.com/HasthoRahtomo/Mainstore-PHP-",
  },
  {
    id: 4,
    image: "./img/project/Fruit information search.png",
    title: "Fruit Searcher",
    language: "HTML, JS",
    description: "This website can display information about various fruits.",
    descriptionDetail: "Fruit information searcher is a website that is fully created using chatGPT version 3.5. This project aims to find out how high chatGPT version 3.5 is in understanding long contexts and the consistency of the code provided.",
    descriptionDetail2: "Almost all parts except images are provided by chatGPT, including code, file structure and file naming, and displayed fruit information. I also provide any prompts that I input into chatGPT, of course not all but the prompts displayed build about 60 - 70% of the total website. The rest are prompts to determine matching colors, styles, and inspiration.",
    githubLink:"https://github.com/HasthoRahtomo/Data-buah",
  },
  {
    id: 5,
    image: "./img/project/ApiAndWebTest.png",
    title: "Demoblaze Test",
    language: "Cucumber",
    description: "testing script using cucumber and selenium.",
    descriptionDetail: "This project was created to perform automation testing for the demoblaze.com website. This project uses Cucumber, Selenium and restAssured to adapt to perform API and UI testing.",
    descriptionDetail2: "By using Github Action CI/CD, this project can be run without having to clone the project and run locally. The report generated has also been deployed, ensuring that the project can run without having to prepare anything.",
    githubLink:"https://github.com/HasthoRahtomo/Api-UI-Demoblaze",
  },
  {
    id: 6,
    image: "./img/project/Online Game WD Database System.png",
    title: "Online Game DB",
    language: "SQL",
    description: "Database for Online Game WD project.",
    descriptionDetail: "This is a database for WD online game project. This database uses SQL from SQL server management studio. Just like the previous database, this database already has views, triggers to ensure that data is easy to retrieve but remains secure.",
    pptLink: "./docs/online game wd db.pdf",
  },
  {
    id: 7,
    image: "./img/project/Online Game WD v2.png",
    title: "Online Game WD",
    language: "C#, ASP.net",
    description: "Online game WD is a website for playing casino online.",
    descriptionDetail: "WD online game is made using C# which is connected to a SQL database using ADO.net. This project is developed using the MVC method, so the resulting code is neater and easier to develop.",
    descriptionDetail2: "WD online game has a unique feature for logging in, namely using an RFID card attached to a special machine. All games provided are based on probability and cannot be set in probability, so it can be said that this website upholds honesty and transparency.",
    githubLink:"https://github.com/HasthoRahtomo/Casino-MVC-",
  },
  {
    id: 8,
    image: "./img/project/Online Game Admin.png",
    title: "Game Admin",
    language: "C#, ASP.net",
    description: "Admin page for Online Game WD project.",
    descriptionDetail: "This is the admin page for the Online Game WD project. This project is used to view data about coin rotation, accounts, game percentages, and winning history.",
    descriptionDetail2: "In this project, you can also perform other functionalities, such as changing user names, doing top-ups, etc. For a feature that requires a special user, just like the client version, the admin must have the card that you want to change and attach it to the RFID card reader.",
    githubLink:"https://github.com/HasthoRahtomo/online-game-admin"
  },
  {
    id: 9,
    image: "./img/project/Wajan.png",
    title: "Wajan",
    language: "HTML",
    description: "Wajan is a website that provides information about Indonesian food.",
    descriptionDetail: "Wajan is a website that provides information about Indonesian food. This website was created to participate in a competition with the theme 'Indonesian culture'. This website was created by our team consisting of three people with different backgrounds.",
    githubLink:"https://github.com/Wajan-Indonesia/Wajan_web",
  },
  {
    id: 10,
    image: "./img/project/Webmaker.png",
    title: "Webmaker",
    language: "HTML",
    description: "Webmaker is a service project for web creation.",
    descriptionDetail: "Webmaker is a service project for website creation. This project prioritizes design by implementing the use of bootstrap in it. This website also provides parallax.",
    pptLink: "./docs/G2 Webmaker.pdf",
  },
];
